[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://dmbbsrcwqpmdxqtzvtqj.supabase.co; style-src 'self' 'unsafe-inline' data:; font-src 'self' data:; img-src 'self' data:; connect-src 'self' https://dmbbsrcwqpmdxqtzvtqj.supabase.co; object-src 'none';"
